[binding] Fix missing ifdef to use j1939 feature
[   63s] /home/abuild/rpmbuild/BUILD/rp-can-low-level-8.0.1/low-can-binding/binding/low-can-cb.cpp:87:16: error: 'class application_t' has no member named 'set_default_j1939_ecu'
[   63s]    application->set_default_j1939_ecu(ecu);

Change-Id: I5dc92fe0a1fbc89fc708dfe3899d23c4c23cbb99
Signed-off-by: Romain Forlot <romain.forlot@iot.bzh>